x=c(20,15,8,10,5)
mean(x)
sd(x)
View(mtcars)
summary(mtcars)
scale(mtcars)
plot(iris$Sepal.Length)
d=scale(iris$Sepal.Length)
plot(d)
plot(iris$Sepal.Length)
d=scale(iris$Sepal.Length)
plot(d)
View(iris)
colr=c("red","green","orange")
plot(iris$Sepal.Length,iris$Sepal.Width,col=colr)
boxplot(iris$Sepal.Length~iris$Species)
table(cars)
p=table(iris$Species)
barplot(p,col = colr)
pie(p,col = colr)
datasetname=read.csv(file.choose(),header = TRUE)
pairs(Cars)
x=c(1,2,3,4,5)
y=c(6,7,8,9,10)
cor.test(x,y)
cor.test(iris$Sepal.Length,iris$Sepal.Width)
cor.test(iris$Sepal.Length,iris$Petal.Length)
cor.test(Cars$HP,Cars$MPG)
cor.test(Cars$HP,Cars$SP)
cor.test(Cars$VOL,Cars$WT)
men=c(100,120,60)
women=c(350,200,90)
survey=as.data.frame(rbind(men,women))
names(survey)=c("chocalate","stawberry","vanila")
survey
chisq.test(survey)
chisq.test(mtcars$vs,mtcars$am)

View(x)
