pairs(Cars)
m2=lm(SP~HP+MPG+VOL+WT,data=Cars)
summary(m2)
m2=lm(SP~HP+MPG+WT,data=Cars)
summary(m2)
m3=lm(SP~HP+MPG+VOL,data=Cars)
summary(m3)
predict(m2,interval = "pre")
predict(m2,data.frame(VOL=90,WT=30,HP=52,MPG=48),INTERVAL="pre")
View(iris)
pairs(iris)
p1=lm(Sepal.Length~Sepal.Width+Petal.Length+Petal.Width,data = iris)
summary(p1)
p1=lm(Sepal.Length~Sepal.Width+Petal.Length+Petal.Width,data = iris)
influenceIndexPlot(p1)
p1=lm(Sepal.Length~Sepal.Width+Petal.Length+Petal.Width,data = iris[-c(135,142,107,118,132),])
summary(p1)


