m=lm(strength~cement+slag+ash+water+superplastic+coarseagg+fineagg+age,data = concrete)
summary(m)
m1=lm(log(strength)~cement+slag+ash+water+superplastic+coarseagg+fineagg+age,data = concrete)
summary(m1)
m2=lm(strength~log(cement+slag+ash+water+superplastic+coarseagg+fineagg+age),data = concrete)
summary(m2)
m=lm(strength~cement+slag+ash+water+superplastic+coarseagg+fineagg+age,data = concrete)
influenceIndexPlot(m)
m=lm(strength~cement+slag+ash+water+superplastic+coarseagg+fineagg+age,data = concrete[-c(134,902,193,507,324,463),])
summary(m)
pairs(concrete)
